#!/bin/bash
Xephyr  -resizeable -dpi 50 "$2" &
unset HOME
export HOME=/root
export DISPLAY="$2"
echo 'GUI Will boot in 2 seconds,Plase resize X Window'
sleep 2
sudo chroot  "$1"  /desktop  &
sudo chroot  "$1"
